### ISSUE TITLE
Issues with External Rom Plugin

### ISSUE THREAD

**Issue by TyroneSama** [ircluzar/RTC3#3]
I've been running into issues when trying to use any of the External ROM plugins with RTC 3.0. I've attached some screenshots of the errors I'm getting. These are happening on a clean installation via the RTC Launcher, regardless of the ROM I use, on default settings.

![2017-09-26_20-49-04-vinesauce_rom_corruptor](https://user-images.githubusercontent.com/8174023/30895000-26a5b424-a2fc-11e7-80c5-2496d4641374.png)

![2017-09-26_20-49-33-rtc__attached_mode](https://user-images.githubusercontent.com/8174023/30895012-39e476f6-a2fc-11e7-94ba-2f38c0e74183.png)

I'm mainly interested in using VSRC or VSRC Classic, but have tried on ChainChomp and VineCorrupt as well, with similar results (errors or outright crashes). Sorry if this is the wrong place to be looking for support / submitting bug reports, but I couldn't find anything on the Redscientist page. If you need any more information from me, please let me know!

**Comment by ircluzar** [comment]
hi, you most likely don't have both processes allowed in the windows
firewall. rtc and the plugins communicate via tcp. this is documented on
the official guide at http://corrupt.wiki

**Comment by TyroneSama** [comment]
All plugins, StandaloneRTC, and EmuHawk are allowed through Windows Firewall—I've allowed everything that brought up a prompt. corrupt.wiki has been down since yesterday (at least) because of cert errors, so if there are more detailed troubleshooting steps, I wasn't able to find them.

**Comment by ircluzar** [comment]
we currently have an ssl problem with the wiki. a ticket was opened with
the hosting provider.

I recommend you temporary disable your firewall, just to confirm if this is
the cause of the issue.
If it is, you might need to go into advanced firewall settings and force it
back open.
Some antivirus software also include firewall features, maybe look at that
too.

In case of doubt, delete the entire program and redownload it.

Give us feedback on the problem please.

**Comment by TyroneSama** [comment]
Okay, here's everything that I've tried.
- disabled Windows Firewall entirely
- deleted and redownloaded the entire program, several times
- ran RTC as Administrator
- manually removed and re-added the firewall rules allowing the RTC processes
- ran RTC from each of my connected drives
- tried the standalone .zip version instead of the version downloaded from RTC Launcher
- reset to "Factory Default" using the .bat / button in RTC Launcher
- tried both Attached and Detached mode

If there are logs or debug information that I can send your way, please let me know and I'll dig that up as well.

![2017-09-28_13-31-02-windows_firewall](https://user-images.githubusercontent.com/8174023/30989090-5332b450-a451-11e7-948d-53f2a3a5680f.png)

**Comment by ircluzar** [comment]
that's really weird.. is there a file in your Bizhawk folder called
ExternalCorrupt.exe?

if there is not then it means your antivirus has blocked it lr deleted it.

otherwise, this error most likely means that the two process couldnt
establish communication via UDP.

were you able to use the external rom plugins from the older version?

**Comment by TyroneSama** [comment]
There is an ExternalCorrupt.exe in my BizHawk folder. I downloaded RTC078 through the RTC Launcher and got the same error when using the External ROM Plugin there as well.

![2017-09-28_21-25-40-bizhawk](https://user-images.githubusercontent.com/8174023/31000867-ea5db888-a493-11e7-98a8-c40f74d021f9.png)

Aside: I did a little poking around on my own, and noticed that the config file generated by the Vinesauce ROM Corruptor plugin (VinesauceROMCorruptor.txt in RTC300/BizHawk) seemed a little bizzare—referencing a ROM that doesn't exist as the "emulator to run". Sorry if this is irrelevant, but it seemed strange to me.

```
textBox_RomDirectory.Text=
textBox_SaveLocation.Text=Mega Man 2.nes
textBox_EmulatorToRun.Text=D:\Programs\VinesauceRTC\VERSIONS\RTC300\BizHawk\CorruptedROM.rom
SettingSaveDirectory=
HotkeyEnabled=False
Hotkey=Space
HotkeyAction=AddStart
```

**Comment by ircluzar** [comment]
oh! could it be possible that your rom is in a zip file? if so, extract it
and try again with the unzipped rom. from the textfile you sent me, it
seems that there is a pipe character in the filename that misplaced the
information in the udp packet. maybe because the rom is in an archive such
as a zip or 7z?

**Comment by TyroneSama** [comment]
None of the ROMs I've tried have been in archives. Is there any other reason that would happen?

**Comment by ircluzar** [comment]
well, right now the only clue i have is this text file you made from VSRC.
It clearly shows that the loaded values in VSRC are wrong. This seems to
show that while UDP communication works, the data it sends seems to be
invalid due to a pipe symbol in the packet.

Can you give me the full path of the rom you are using?
Can you try copying the rom in the RTC folder and see what happens if you
run it from there?

**Comment by TyroneSama** [comment]
I was running the RTC from `D:\Programs\VinesauceRTC\RTC_Launcher.exe`, with my ROM at `D:\Documents\Scraps\Mega Man 2.nes`. I tried moving the ROM to the same folder as RTC_Launcher, and after that didn't work, into the BizHawk folder. No luck just yet.

**Comment by ircluzar** [comment]
So from my understanding, you had this problem in 0.78, and it still happens in 3.00 so this isn't a new bug
We know there is UDP communication because you have some relevant data in the VSRC save txt file but the data seems to be broken.
The way the UDP communication works with plugins uses strings split by the character "|" (pipe character) and my understanding of the issue right now, from the data in the TXT is that there is a pipe somewhere before your rom name, otherwise it would show as "D:\Documents\Scraps\Mega Man 2.nes" and not as "Mega Man 2.nes"

At this point i'm kind of out of ideas, the issue is clearly related to either your computer or to something you do when you open the rom. From the looks of it, it does sound like you are opening the rom from sorts of a zipfile as bizhawk detects the filename as yourzipfilename.zip|fileinsidethezip.nes

The best i could do at this point would be to check with you via teamviewer to see what the hell is happenning. you can get ahold of us at http://discord.corrupt.wiki

**Comment by TyroneSama** [comment]
After a little more hair-pulling, turns out that I was using a romset from a fucking psychopath, where the ROMs were double-layer zipped with the wrong extension (e.g. `MM2.zip > MM2.nes (ACTUALLY A ZIP FILE) > MM2.nes`).

Thanks for pointing me in the right direction. I know my case is sort of one-in-a-million, but it might be worthwhile to flash up a message if someone's trying to use the external ROM plugin with an archived ROM?
